
export const USER_SIGNUP_START = 'USER_SIGNUP_START';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';
export const USER_SIGNUP_CLEANUP = 'USER_SIGNUP_CLEANUP';

export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const CLEAN_UP_LOGIN_ERROR = 'CLEAN_UP_LOGIN_ERROR';
 
export const REFRESH_USER_PROFILE = 'REFRESH_USER_PROFILE'
export const SET_ACTIVE = 'SET_ACTIVE'
export const SET_ACTIVE_PROFILE = 'SET_ACTIVE_PROFILE'


export const FETCH_NOTIFICATIONS_START = 'FETCH_NOTIFICATIONS_START'
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS'
export const FETCH_NOTIFICATIONS_COUNT_SUCCESS = 'FETCH_NOTIFICATIONS_COUNT_SUCCESS'
export const FETCH_NOTIFICATIONS_FAIL = 'FETCH_NOTIFICATIONS_FAIL'
export const FETCH_NOTIFICATIONS_CLEANUP = 'FETCH_NOTIFICATIONS_CLEANUP'
export const MARK_AS_READ = 'MARK_AS_READ'
 